In [1]:
import pandas as pd

In [13]:
base = pd.read_csv ("https://www.quandl.com/api/v3/datasets/MULTPL/SP500_DIV_YIELD_MONTH.csv?api_key=TBLavZNarehnwBsVjw8F")

In [12]:
base

,Trade Date,Index Value,High,Low,Total Market Value,Dividend Market Value
0,2019-10-29,0.00,0.0,0.0,0.0,0.0
1,2019-10-25,8029.22,0.0,0.0,0.0,0.0
2,2019-10-24,7966.72,0.0,0.0,0.0,0.0
3,2019-10-23,7889.47,0.0,0.0,0.0,0.0
4,2019-10-22,7874.62,0.0,0.0,0.0,0.0
5,2019-10-21,7940.33,0.0,0.0,0.0,0.0
6,2019-10-18,7868.49,0.0,0.0,0.0,0.0
7,2019-10-17,7942.14,0.0,0.0,0.0,0.0
8,2019-10-16,7920.21,0.0,0.0,0.0,0.0
9,2019-10-15,7942.85,0.0,0.0,0.0,0.0
10,2019-10-14,7842.33,0.0,0.0,0.0,0.0
11,2019-10-11,7843.87,0.0,0.0,0.0,0.0
12,2019-10-10,7740.36,0.0,0.0,0.0,0.0
13,2019-10-09,7690.53,0.0,0.0,0.0,0.0
14,2019-10-08,7604.27,0.0,0.0,0.0,0.0
15,2019-10-07,7725.13,0.0,0.0,0.0,0.0
16,2019-10-04,7754.10,0.0,0.0,0.0,0.0
17,2019-10-03,7638.39,0.0,0.0,0.0,0.0
18,2019-10-02,7550.79,0.0,0.0,0.0,0.0
19,2019-10-01,7684.14,0.0,0.0,0.0,0.0
20,2019-09-30,7749.45,0.0,0.0,0.0,0.0
21,2019-09-27,7681.58,0.0,0.0,0.0,0.0
22,2019-09-26,7771.99,0.0,0.0,0.0,0.0
23,2019-09-25,7803.54,0.0,0.0,0.0,0.0
24,2019-09-24,7710.04,0.0,0.0,0.0,0.0
25,2019-09-23,7818.61,0.0,0.0,0.0,0.0
26,2019-09-20,7823.55,0.0,0.0,0.0,0.0
27,2019-09-19,7901.79,0.0,0.0,0.0,0.0
28,2019-09-18,7888.56,0.0,0.0,0.0,0.0
29,2019-09-17,7888.79,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...
689,2017-02-01,5152.69,0.0,0.0,0.0,0.0
690,2017-01-31,5116.77,0.0,0.0,0.0,0.0
691,2017-01-30,5129.33,0.0,0.0,0.0,0.0
692,2017-01-27,5168.06,0.0,0.0,0.0,0.0
693,2017-01-26,5156.92,0.0,0.0,0.0,0.0
694,2017-01-25,5151.47,0.0,0.0,0.0,0.0
695,2017-01-24,5101.06,0.0,0.0,0.0,0.0
696,2017-01-23,5065.70,0.0,0.0,0.0,0.0
697,2017-01-20,5063.20,0.0,0.0,0.0,0.0
698,2017-01-19,5051.17,0.0,0.0,0.0,0.0
699,2017-01-18,5055.85,0.0,0.0,0.0,0.0
700,2017-01-17,5044.65,0.0,0.0,0.0,0.0
701,2017-01-13,5059.51,0.0,0.0,0.0,0.0
702,2017-01-12,5041.43,0.0,0.0,0.0,0.0
703,2017-01-11,5050.21,0.0,0.0,0.0,0.0
704,2017-01-10,5035.17,0.0,0.0,0.0,0.0
705,2017-01-09,5024.90,0.0,0.0,0.0,0.0
706,2017-01-06,5007.08,0.0,0.0,0.0,0.0
707,2017-01-05,4964.95,0.0,0.0,0.0,0.0
708,2017-01-04,4937.20,0.0,0.0,0.0,0.0
709,2017-01-03,4911.33,0.0,0.0,0.0,0.0
710,2016-12-30,4863.62,0.0,0.0,0.0,0.0
711,2016-12-29,4918.28,0.0,0.0,0.0,0.0
712,2016-12-28,4926.29,0.0,0.0,0.0,0.0
713,2016-12-27,4965.81,0.0,0.0,0.0,0.0
714,2016-12-23,4940.02,0.0,0.0,0.0,0.0
715,2016-12-22,4934.39,0.0,0.0,0.0,0.0
716,2016-12-21,4948.90,0.0,0.0,0.0,0.0
717,2016-12-20,4953.80,0.0,0.0,0.0,0.0
718,2016-12-19,4934.85,0.0,0.0,0.0,0.0

In [7]:
base.Instrumento.unique()

array(['vara de pescar e botas', 'faca', 'arma de fogo',
       'faca (peixeira)', 'soda caústica + força bruta',
       'socos, pontapés e martelo', 'cabo de cortadeira',
       'asfixia com fio elétrico + balde d"água', 'espingarda',
       'cabo de vassoura, garrafa de vidro', 'canivete', 'envenenamento',
       'Diazepan, instumento contundente, afogamento'], dtype=object)

In [10]:
base.Instrumento.value_counts()

faca                                            12
arma de fogo                                    11
cabo de cortadeira                               1
soda caústica + força bruta                      1
envenenamento                                    1
canivete                                         1
asfixia com fio elétrico + balde d"água          1
espingarda                                       1
socos, pontapés e martelo                        1
faca (peixeira)                                  1
Diazepan, instumento contundente, afogamento     1
cabo de vassoura, garrafa de vidro               1
vara de pescar e botas                           1
Name: Instrumento, dtype: int64